# Generated by Django 4.2.10 on 2024-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_de_contratatacion', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
                ('salario', models.DecimalField(decimal_places=5, max_digits=20)),
                ('IHSS', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=50)),
            ],
        ),
    ]
