# Generated by Django 4.2.10 on 2024-04-13 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales ni numeros, solo letras', regex='^[a-zA-Z]+$'), django.core.validators.RegexValidator(message='La primera letra debe ser mayuscula, el campo no permite letras mayusculas luego de la primera letra', regex='^[A-Z][a-z]*$'), django.core.validators.RegexValidator(message='No se permite mas de una palabra en el campo.', regex='^[^\\s]+$'), django.core.validators.RegexValidator(message='El campo no permite tres mismas letras seguidas o mas.', regex='^(?:(?!(\\w)\\1\\1).)+$')]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='correo_electronico',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='direccion',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales, solo letras y numeros', regex='^[a-zA-Z0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales ni numeros, solo letras', regex='^[a-zA-Z]+$'), django.core.validators.RegexValidator(message='La primera letra debe ser mayuscula, el campo no permite letras mayusculas luego de la primera letra', regex='^[A-Z][a-z]*$'), django.core.validators.RegexValidator(message='No se permite mas de una palabra en el campo.', regex='^[^\\s]+$'), django.core.validators.RegexValidator(message='El campo no permite tres mismas letras seguidas o mas.', regex='^(?:(?!(\\w)\\1\\1).)+$')]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='nombre_de_empresa',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales, solo letras y numeros', regex='^[a-zA-Z0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='telefono',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El numero ingresado no es válido, el numero de telefono debe ser de 8 digitos y solo numeros.', regex='^[0-9]{8}$')]),
        ),
    ]
