# Generated by Django 4.2.10 on 2024-04-13 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_methods',
            name='descripcion',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales ni numeros', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='payment_methods',
            name='tipo_metodo_pago',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales ni numeros, solo letras mayusculas', regex='^[A-Z]+$')]),
        ),
    ]
