# Generated by Django 4.2.10 on 2024-04-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_products_id_impuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cambio', models.CharField(max_length=50)),
                ('descripcion_cambio', models.CharField(max_length=50)),
                ('fecha_de_vencimiento_cambio', models.CharField(max_length=50)),
                ('stock_cambio', models.CharField(max_length=50)),
                ('precio_cambio', models.CharField(max_length=50)),
                ('categoria_cambio', models.CharField(max_length=50)),
                ('proveedor_cambio', models.CharField(max_length=50)),
                ('Fecha_Hora', models.DateTimeField(auto_now_add=True)),
                ('foranea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
