# Generated by Django 4.2.10 on 2024-04-13 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_methods', '0002_alter_payment_methods_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales ni numeros, solo letras', regex='^[a-zA-Z]+$'), django.core.validators.RegexValidator(message='La primera letra debe ser mayuscula, el campo no permite letras mayusculas luego de la primera letra', regex='^[A-Z][a-z]*$'), django.core.validators.RegexValidator(message='No se permite mas de una palabra en el campo.', regex='^[^\\s]+$'), django.core.validators.RegexValidator(message='El campo no permite tres mismas letras seguidas o mas.', regex='^(?:(?!(\\w)\\1\\1).)+$')])),
                ('apellido', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales ni numeros, solo letras', regex='^[a-zA-Z]+$'), django.core.validators.RegexValidator(message='La primera letra debe ser mayuscula, el campo no permite letras mayusculas luego de la primera letra', regex='^[A-Z][a-z]*$'), django.core.validators.RegexValidator(message='No se permite mas de una palabra en el campo.', regex='^[^\\s]+$'), django.core.validators.RegexValidator(message='El campo no permite tres mismas letras seguidas o mas.', regex='^(?:(?!(\\w)\\1\\1).)+$')])),
                ('fecha_de_nacimiento', models.DateField(max_length=50)),
                ('direccion', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales, solo letras y numeros', regex='^[a-zA-Z0-9\\s]+$')])),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('metodos_pago', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment_methods.payment_methods')),
            ],
        ),
    ]
