# Generated by Django 4.2.10 on 2024-04-14 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_alter_payment_methods_descripcion_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='metodos_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_methods.payment_methods'),
        ),
    ]
