# Generated by Django 4.2.10 on 2024-04-14 20:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromDisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepromocion_descuento', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales, solo letras y numeros', regex='^[a-zA-Z0-9\\s]+$')])),
                ('porcentaje', models.DecimalField(choices=[(Decimal('0.10'), '10%'), (Decimal('0.15'), '15%'), (Decimal('0.20'), '20%'), (Decimal('0.25'), '25%'), (Decimal('0.30'), '30%'), (Decimal('0.35'), '35%'), (Decimal('0.40'), '40%'), (Decimal('0.45'), '45%'), (Decimal('0.50'), '50%'), (Decimal('0.60'), '60%'), (Decimal('0.70'), '70%'), (Decimal('0.75'), '75%'), (Decimal('0.80'), '80%'), (Decimal('0.90'), '90%'), (Decimal('0.95'), '95%')], decimal_places=2, max_digits=4)),
                ('promocion_descuento', models.CharField(choices=[('P', 'Promocion'), ('D', 'Descuento'), ('O', 'Otro')], max_length=20)),
            ],
        ),
    ]
