# Generated by Django 4.2.10 on 2024-04-29 03:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentopromotionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promdisc',
            name='porcentaje',
            field=models.DecimalField(choices=[(Decimal('0.0'), '0%'), (Decimal('0.10'), '10%'), (Decimal('0.15'), '15%'), (Decimal('0.20'), '20%'), (Decimal('0.25'), '25%'), (Decimal('0.30'), '30%'), (Decimal('0.35'), '35%'), (Decimal('0.40'), '40%'), (Decimal('0.45'), '45%'), (Decimal('0.50'), '50%'), (Decimal('0.60'), '60%'), (Decimal('0.70'), '70%'), (Decimal('0.75'), '75%'), (Decimal('0.80'), '80%'), (Decimal('0.90'), '90%'), (Decimal('0.95'), '95%')], decimal_places=2, max_digits=4),
        ),
    ]
