# Generated by Django 4.2.10 on 2024-04-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0003_alter_sale_precio_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_cambio', models.CharField(max_length=50)),
                ('producto_cambio', models.CharField(max_length=50)),
                ('cantidad_producto_cambio', models.CharField(max_length=50)),
                ('precio_venta_cambio', models.CharField(max_length=50)),
                ('fecha_venta_cambio', models.CharField(max_length=50)),
                ('metodo_pago_cambio', models.CharField(max_length=50)),
                ('total_venta_cambio', models.CharField(max_length=50)),
                ('sucursal_cambio', models.CharField(max_length=50)),
                ('usuario_cambio', models.CharField(max_length=50)),
                ('num_factura_cambio', models.CharField(max_length=50)),
                ('Fecha_Hora', models.DateTimeField(auto_now_add=True)),
                ('foranea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sale.sale')),
            ],
        ),
    ]
