# Generated by Django 4.2.10 on 2024-04-14 21:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_products_id_impuesto_and_more'),
        ('branch_offices', '0002_branch_offices_ciudad_alter_branch_offices_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(default='', max_length=50)),
                ('cantidadinventario', models.IntegerField(default=0)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('cantidadminima', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima')),
                ('cantidadmaxima', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Máxima')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Producto')),
                ('idsucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branch_offices.branch_offices', verbose_name='Sucursal')),
            ],
        ),
    ]
