# Generated by Django 4.2.10 on 2024-04-13 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales ni numeros', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tasa',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El numero ingresado no es válido, no se permite ningun caracter especial, solo numeros de 4 digitos Ej: 12.45.', regex='^[0-9]{2}\\.[0-9]{2}+$')]),
        ),
    ]
