# Generated by Django 4.2.10 on 2024-04-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_tax_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax_history',
            old_name='Fecha_Hora',
            new_name='fecha_hora',
        ),
    ]
