# Generated by Django 4.2.10 on 2024-04-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0006_rename_fecha_hora_tax_history_fecha_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax_history',
            old_name='fecha_hora',
            new_name='Fecha_Hora',
        ),
    ]
