# Generated by Django 4.2.10 on 2024-04-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0008_tax_history_foranea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax_History',
        ),
    ]
