# Generated by Django 4.2.10 on 2024-04-21 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0009_delete_tax_history'),
        ('productsdetail', '0001_initial'),
        ('clients', '0002_alter_clients_metodos_pago'),
        ('payment_methods', '0002_alter_payment_methods_descripcion_and_more'),
        ('descuentopromotionapp', '0001_initial'),
        ('users', '0002_remove_users_ihss_users_horario_trabajo_and_more'),
        ('cai', '0001_initial'),
        ('products', '0003_remove_products_stock_alter_products_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_factura', models.CharField(blank=True, max_length=20)),
                ('fechaemision', models.DateTimeField(auto_now_add=True)),
                ('RTN', models.CharField(blank=True, max_length=20)),
                ('idcai', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cai.cai')),
                ('idcliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clients.clients')),
                ('iddescuento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='descuentopromotionapp.promdisc')),
                ('idempleado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.users')),
                ('idmetododepago', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment_methods.payment_methods')),
                ('idproducts', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.products')),
                ('idproductsdetail', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='productsdetail.productsdetail')),
                ('idtax', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tax.tax')),
            ],
        ),
    ]
