# Generated by Django 4.2.10 on 2024-04-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_remove_factura_idproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
