# Generated by Django 4.2.10 on 2024-04-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_factura_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
