# Generated by Django 4.2.10 on 2024-04-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_factura_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='Notas',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
