# Generated by Django 4.2.10 on 2024-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_factura_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Notas',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
