# Generated by Django 4.2.10 on 2024-04-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('descuentopromotionapp', '0001_initial'),
        ('tax', '0009_delete_tax_history'),
        ('productsdetail', '0001_initial'),
        ('users', '0002_remove_users_ihss_users_horario_trabajo_and_more'),
        ('clients', '0002_alter_clients_metodos_pago'),
        ('cai', '0001_initial'),
        ('payment_methods', '0002_alter_payment_methods_descripcion_and_more'),
        ('factura', '0007_alter_factura_idcai_alter_factura_idcliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Notas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='RTN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fechaemision',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idcai',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cai.cai'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idcliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clients'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iddescuento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='descuentopromotionapp.promdisc'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idempleado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.users'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idmetododepago',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_methods.payment_methods'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idproductsdetail',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='productsdetail.productsdetail'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idtax',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tax.tax'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='num_factura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
