# Generated by Django 4.2.10 on 2024-04-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_alter_factura_notas_alter_factura_rtn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
