# Generated by Django 4.2.10 on 2024-04-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0014_client_settings_invoice_paymentterms_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('14 dias', '14 dias'), ('30 dias', '30 dias'), ('60 dias', '60 dias')], default='14 dias', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ACTUAL', 'ACTUAL'), ('EMAIL_SENT', 'EMAIL_SENT'), ('ATRASADO', 'ATRASADO'), ('PAGADO', 'PAGADO')], default='ACTUAL', max_length=100),
        ),
    ]
