# Generated by Django 4.2.10 on 2024-04-29 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0015_alter_invoice_paymentterms_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='El requiere 14 digitos no letras ni caracteres especiales', regex='^\\d{14}$')]),
        ),
    ]
