# Generated by Django 4.2.10 on 2024-04-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsdetail', '0001_initial'),
        ('factura', '0016_alter_invoice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('Tegucigalpa, Distrito Central', 'Tegucigalpa, Distrito Central'), ('Comayaguela, Distrito Central', 'Free Comayaguela, Distrito Central')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('Lps.', 'Lempiras')], default='Lps.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productsdetail.productsdetail'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='province',
            field=models.CharField(blank=True, choices=[('Tegucigalpa, Distrito Central', 'Tegucigalpa, Distrito Central'), ('Comayaguela, Distrito Central', 'Free Comayaguela, Distrito Central')], max_length=100),
        ),
    ]
