# Generated by Django 4.2.10 on 2024-04-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsdetail', '0002_alter_productsdetail_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdetail',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
