# Generated by Django 4.2.10 on 2024-04-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devolucion', '0002_alter_devolucion_cantidad_retornada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_cambio', models.CharField(max_length=50)),
                ('cantidad_retornada_cambio', models.CharField(max_length=50)),
                ('Fecha_Hora', models.DateTimeField(auto_now_add=True)),
                ('foranea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devolucion.devolucion')),
            ],
        ),
    ]
