# Generated by Django 4.2.10 on 2024-04-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cambio', models.CharField(max_length=50)),
                ('tasa_cambio', models.CharField(max_length=50)),
                ('Fecha_Hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
