# Generated by Django 4.2.10 on 2024-04-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_history', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax_History',
        ),
    ]
