# Generated by Django 4.2.10 on 2024-04-14 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0009_delete_tax_history'),
        ('tax_history', '0002_delete_tax_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cambio', models.CharField(max_length=50)),
                ('tasa_cambio', models.CharField(max_length=50)),
                ('Fecha_Hora', models.DateTimeField(auto_now_add=True)),
                ('foranea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tax.tax')),
            ],
        ),
    ]
