# Generated by Django 4.2.10 on 2024-04-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_offices', '0002_branch_offices_ciudad_alter_branch_offices_direccion_and_more'),
        ('products', '0002_remove_products_id_impuesto_and_more'),
        ('payment_methods', '0002_alter_payment_methods_descripcion_and_more'),
        ('users', '0002_remove_users_ihss_users_horario_trabajo_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(default=0)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('fecha_venta', models.DateField(max_length=50)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('num_factura', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='clients.clients')),
                ('metodo_pago', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='payment_methods.payment_methods')),
                ('producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='products.products')),
                ('sucursal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='branch_offices.branch_offices')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.users')),
            ],
        ),
    ]
