# Generated by Django 4.2.10 on 2024-04-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='num_factura',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
