# Generated by Django 4.2.10 on 2024-04-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_num_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
