# Generated by Django 4.2.10 on 2024-04-13 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_codigo_postal_alter_city_nombre_ciudad'),
        ('branch_offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_offices',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='city.city'),
        ),
        migrations.AlterField(
            model_name='branch_offices',
            name='direccion',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales, solo letras y numeros', regex='^[a-zA-Z0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='branch_offices',
            name='nombre_sucursal',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales, solo letras y numeros', regex='^[a-zA-Z0-9\\s]+$')]),
        ),
    ]
