# Generated by Django 4.2.10 on 2024-04-14 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_alter_suppliers_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cai', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='CAI incorrecto ingrese uno utilizando el formato correcto. Ej.123456-ABCDEF-012345-ABCDEF-012345-AB', regex='^[0-9A-Z]{6}-[0-9A-Z]{6}-[0-9A-Z]{6}-[0-9A-Z]{6}-[0-9A-Z]{6}-[0-9A-Z]{2}$')])),
                ('nombre_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.suppliers')),
            ],
        ),
    ]
