# Generated by Django 4.2.10 on 2024-03-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.IntegerField(max_length=100)),
                ('fecha_pedido', models.DateField(max_length=10)),
                ('dias_trabajo', models.CharField(max_length=150)),
                ('duracion_jornada', models.CharField(max_length=10)),
                ('tipo_jornada', models.CharField(choices=[('Matutina', 'Jornada Matutina'), ('Vespertina', 'Jornada Vespertina'), ('Nocturna', 'Jornada Nocturna')], max_length=20)),
            ],
        ),
    ]
