# Generated by Django 4.2.10 on 2024-04-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_alter_payment_methods_descripcion_and_more'),
        ('cai', '0001_initial'),
        ('users', '0002_remove_users_ihss_users_horario_trabajo_and_more'),
        ('order', '0002_alter_order_numero_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.CharField(blank=True, max_length=20)),
                ('fecha_de_pedido', models.DateField(max_length=50)),
                ('estado_pago', models.CharField(choices=[('A', 'Aceptado'), ('D', 'Denegado'), ('P', 'Pendiente')], max_length=20)),
                ('estado_pedido', models.CharField(choices=[('EP', 'En Proceso'), ('ENT', 'Entregado'), ('PRODFALT', 'Productos Faltantes'), ('B', 'Bueno'), ('R', 'Recibido')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('cai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cai.cai')),
                ('metodo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_methods.payment_methods')),
                ('nombre_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
