# Generated by Django 4.2.10 on 2024-04-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_alter_payment_methods_descripcion_and_more'),
        ('cai', '0001_initial'),
        ('users', '0002_remove_users_ihss_users_horario_trabajo_and_more'),
        ('orderdetail', '0001_initial'),
        ('order', '0003_orders_delete_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
