# Generated by Django 4.2.10 on 2024-03-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_de_vencimiento', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('id_proveedor', models.CharField(max_length=1)),
                ('id_impuesto', models.CharField(max_length=50)),
            ],
        ),
    ]
