# Generated by Django 4.2.10 on 2024-04-13 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_fecha_de_modificacion_and_more'),
        ('suppliers', '0002_alter_suppliers_apellido_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id_impuesto',
        ),
        migrations.RemoveField(
            model_name='products',
            name='id_proveedor',
        ),
        migrations.AddField(
            model_name='products',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='suppliers.suppliers'),
        ),
        migrations.AlterField(
            model_name='products',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='descripcion',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales, solo letras y numeros', regex='^[a-zA-Z0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='products',
            name='fecha_de_vencimiento',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El campo no permite caracteres especiales, solo letras y numeros', regex='^[a-zA-Z0-9\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='products',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
